### PR TITLE
fix(pac): default listen on 127.0.0.1, listen on demand

### LINKED ISSUE #149: [Bug] 没有打开系统代理的情况下不应该自动启动PAC服务
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

13.6.9 (22G830)

### 发生问题 mihomo-party 版本

v1.2.13

### 描述

如图未打开系统代理，但是在本地端口列表中显示了10000端口被打开。

image

通过查看代码发现10000端口是给PAC使用的，我认为在系统代理未启用的情况下10000端口不应该被自动创建。

PS: 系统代理打开的情况下，如果代理模式设置为**手动**是否也不应该打开？

### 重现方式

启动程序即可复现

### PR DESCRIPTION
**Pull request by qianlongzt**
fix https://github.com/mihomo-party-org/mihomo-party/issues/149

### CODE REVIEW

File: src/main/resolve/server.ts [hunk 1]
```diff
@@ -41,21 +41,31 @@ export function findAvailablePort(startPort: number): Promise<number> {
   })
 }
 
+let pacServer: http.Server
+
 export async function startPacServer(): Promise<void> {
```
Comment (ghost) [inline src/main/resolve/server.ts:46]: The server should be stop before each start.

**Review by ghost — CHANGES_REQUESTED** [review]

File: src/main/resolve/server.ts (hunk 1 above)
Comment (qianlongzt) [reply src/main/resolve/server.ts:46]: fixed

**Review by ghost — APPROVED** [review]
